;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_spr
	.import		_oam_meta_spr
	.import		_oam_set
	.import		_pad_poll
	.import		_split
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_clear_vram_buffer
	.import		_get_pad_new
	.import		_set_scroll_x
	.import		_set_scroll_y
	.import		_flush_vram_update2
	.import		_read_powerpad
	.export		_powerpad_cur
	.export		_powerpad_old
	.export		_powerpad_new
	.export		_debug_controller
	.export		_debug_controller_new
	.export		_temp_int
	.export		_last_step
	.export		_steps
	.export		_ones_step
	.export		_tens_step
	.export		_hundreds_step
	.export		_thousands_step
	.export		_ten_thousands_step
	.export		_steps_per_minute
	.export		_hundreds_spm
	.export		_tens_spm
	.export		_ones_spm
	.export		_seconds
	.export		_ones_seconds
	.export		_tens_seconds
	.export		_ones_minutes
	.export		_tens_minutes
	.export		_ones_hours
	.export		_tens_hours
	.export		_frame_counter
	.export		_step_button_lockout
	.export		_motion_counter
	.export		_time_since_button_press
	.export		_motion
	.export		_was_running
	.export		_was_walking
	.export		_mph
	.export		_sprite_timer
	.export		_sprite_frame_counter
	.export		_scroll_x
	.export		_largeindex
	.export		_scroll_timer
	.export		_add_step
	.export		_add_second
	.export		_initial_steps_conversion
	.export		_initial_timer_conversion
	.export		_check_motion
	.export		_update_motion
	.export		_load_room
	.export		_draw_sprite
	.export		_draw_hud
	.export		_process_controller
	.export		_set_sprite_zero
	.export		_update_steps_per_minute
	.export		_track
	.export		_marathon_man__run1_data
	.export		_marathon_man__run2_data
	.export		_marathon_man__run3_data
	.export		_marathon_man__run4_data
	.export		_marathon_man__run5_data
	.export		_marathon_man__run6_data
	.export		_marathon_man__walk1_data
	.export		_marathon_man__walk2_data
	.export		_marathon_man__walk3_data
	.export		_marathon_man__walk4_data
	.export		_palette_sprites
	.export		_palette_bg
	.export		_process_powerpad
	.export		_main

.segment	"RODATA"

_track:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$54
	.byte	$49
	.byte	$4D
	.byte	$45
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4D
	.byte	$50
	.byte	$48
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$54
	.byte	$45
	.byte	$50
	.byte	$53
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$4B
	.byte	$43
	.byte	$41
	.byte	$4C
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$50
	.byte	$4D
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$53
	.byte	$43
	.byte	$4F
	.byte	$52
	.byte	$45
	.byte	$3A
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$14
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$5E
	.byte	$5F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$7E
	.byte	$7F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6C
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6C
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6C
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6C
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6C
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6D
	.byte	$6C
	.byte	$5D
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$6A
	.byte	$6B
	.byte	$67
	.byte	$68
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$6B
	.byte	$F1
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$CA
	.byte	$CB
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$64
	.byte	$02
	.byte	$63
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$CA
	.byte	$CB
	.byte	$CC
	.byte	$BD
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$CA
	.byte	$DC
	.byte	$BD
	.byte	$03
	.byte	$AD
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$65
	.byte	$02
	.byte	$A3
	.byte	$A4
	.byte	$A4
	.byte	$A4
	.byte	$A4
	.byte	$A5
	.byte	$65
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$86
	.byte	$87
	.byte	$02
	.byte	$02
	.byte	$7A
	.byte	$7B
	.byte	$7A
	.byte	$7B
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$BB
	.byte	$BC
	.byte	$BD
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$B3
	.byte	$B4
	.byte	$B5
	.byte	$B5
	.byte	$B4
	.byte	$B6
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$02
	.byte	$96
	.byte	$97
	.byte	$02
	.byte	$02
	.byte	$8A
	.byte	$8B
	.byte	$8A
	.byte	$8B
	.byte	$02
	.byte	$B8
	.byte	$B9
	.byte	$BA
	.byte	$CC
	.byte	$03
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$CD
	.byte	$02
	.byte	$63
	.byte	$02
	.byte	$C3
	.byte	$C4
	.byte	$C4
	.byte	$C4
	.byte	$C5
	.byte	$02
	.byte	$65
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$65
	.byte	$63
	.byte	$02
	.byte	$9A
	.byte	$9B
	.byte	$9A
	.byte	$9B
	.byte	$02
	.byte	$02
	.byte	$B8
	.byte	$B9
	.byte	$DC
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$02
	.byte	$02
	.byte	$65
	.byte	$65
	.byte	$D1
	.byte	$D1
	.byte	$D1
	.byte	$D1
	.byte	$D1
	.byte	$D1
	.byte	$D1
	.byte	$C9
	.byte	$BC
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$73
	.byte	$83
	.byte	$85
	.byte	$01
	.byte	$73
	.byte	$73
	.byte	$73
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$73
	.byte	$01
	.byte	$F0
	.byte	$02
	.byte	$63
	.byte	$63
	.byte	$F3
	.byte	$01
	.byte	$E5
	.byte	$01
	.byte	$01
	.byte	$E8
	.byte	$E9
	.byte	$01
	.byte	$F6
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$D3
	.byte	$01
	.byte	$01
	.byte	$85
	.byte	$85
	.byte	$83
	.byte	$01
	.byte	$01
	.byte	$83
	.byte	$83
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$83
	.byte	$D0
	.byte	$D0
	.byte	$02
	.byte	$02
	.byte	$F3
	.byte	$01
	.byte	$01
	.byte	$F6
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$E5
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$E5
	.byte	$74
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$01
	.byte	$75
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$83
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$D0
	.byte	$D0
	.byte	$02
	.byte	$E2
	.byte	$F3
	.byte	$01
	.byte	$01
	.byte	$E4
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$F5
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$85
	.byte	$75
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$83
	.byte	$F0
	.byte	$02
	.byte	$63
	.byte	$65
	.byte	$F3
	.byte	$01
	.byte	$01
	.byte	$E5
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$F5
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$01
	.byte	$72
	.byte	$71
	.byte	$71
	.byte	$72
	.byte	$61
	.byte	$61
	.byte	$62
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$71
	.byte	$71
	.byte	$61
	.byte	$61
	.byte	$61
	.byte	$70
	.byte	$65
	.byte	$63
	.byte	$E2
	.byte	$F3
	.byte	$D4
	.byte	$D4
	.byte	$D2
	.byte	$D4
	.byte	$D4
	.byte	$D4
	.byte	$D4
	.byte	$D4
	.byte	$D2
	.byte	$D4
	.byte	$D4
	.byte	$D4
	.byte	$02
	.byte	$63
	.byte	$63
	.byte	$65
	.byte	$63
	.byte	$63
	.byte	$65
	.byte	$02
	.byte	$64
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$65
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$65
	.byte	$F3
	.byte	$01
	.byte	$F4
	.byte	$01
	.byte	$01
	.byte	$E6
	.byte	$01
	.byte	$01
	.byte	$E3
	.byte	$01
	.byte	$E7
	.byte	$01
	.byte	$77
	.byte	$78
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$78
	.byte	$76
	.byte	$78
	.byte	$79
	.byte	$02
	.byte	$02
	.byte	$63
	.byte	$F2
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$A0
	.byte	$00
	.byte	$00
	.byte	$40
	.byte	$50
	.byte	$FF
	.byte	$FF
	.byte	$AA
	.byte	$21
	.byte	$00
	.byte	$00
	.byte	$04
	.byte	$05
	.byte	$FF
	.byte	$FF
	.byte	$FF
	.byte	$FB
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$AF
	.byte	$AF
	.byte	$AF
	.byte	$AF
	.byte	$A2
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_marathon_man__run1_data:
	.byte	$06
	.byte	$19
	.byte	$08
	.byte	$00
	.byte	$0C
	.byte	$18
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$2B
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$2A
	.byte	$02
	.byte	$F8
	.byte	$10
	.byte	$29
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$3B
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$3A
	.byte	$02
	.byte	$F8
	.byte	$18
	.byte	$39
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$4B
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$4A
	.byte	$02
	.byte	$F8
	.byte	$20
	.byte	$49
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$5B
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$5A
	.byte	$02
	.byte	$F8
	.byte	$28
	.byte	$59
	.byte	$02
	.byte	$F0
	.byte	$28
	.byte	$58
	.byte	$02
	.byte	$F0
	.byte	$30
	.byte	$68
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$69
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$6A
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$6B
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$7B
	.byte	$02
	.byte	$10
	.byte	$38
	.byte	$7C
	.byte	$02
	.byte	$80
_marathon_man__run2_data:
	.byte	$08
	.byte	$1A
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$03
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0B
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0B
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0B
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$A2
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$A1
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$B2
	.byte	$02
	.byte	$F8
	.byte	$18
	.byte	$B0
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$B1
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$C2
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$C1
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$D1
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$D2
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$E2
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$F2
	.byte	$02
	.byte	$00
	.byte	$38
	.byte	$F1
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$E1
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$E0
	.byte	$02
	.byte	$80
_marathon_man__run3_data:
	.byte	$0B
	.byte	$16
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$A6
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$A5
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$B6
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$B5
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$C6
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$C5
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$D6
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$E6
	.byte	$02
	.byte	$10
	.byte	$30
	.byte	$E7
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$F6
	.byte	$02
	.byte	$00
	.byte	$38
	.byte	$F5
	.byte	$02
	.byte	$F8
	.byte	$38
	.byte	$F4
	.byte	$02
	.byte	$F0
	.byte	$38
	.byte	$F3
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$E4
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$E5
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$D5
	.byte	$02
	.byte	$F8
	.byte	$28
	.byte	$D4
	.byte	$02
	.byte	$80
_marathon_man__run4_data:
	.byte	$0C
	.byte	$15
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$AB
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$AA
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$BB
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$BA
	.byte	$02
	.byte	$F8
	.byte	$18
	.byte	$B9
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$CB
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$CA
	.byte	$02
	.byte	$F8
	.byte	$20
	.byte	$C9
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$DB
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$DA
	.byte	$02
	.byte	$F8
	.byte	$28
	.byte	$D9
	.byte	$02
	.byte	$F0
	.byte	$28
	.byte	$D8
	.byte	$02
	.byte	$F0
	.byte	$30
	.byte	$E8
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$E9
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$EA
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$EB
	.byte	$02
	.byte	$10
	.byte	$30
	.byte	$EC
	.byte	$02
	.byte	$10
	.byte	$28
	.byte	$DC
	.byte	$02
	.byte	$10
	.byte	$38
	.byte	$FC
	.byte	$02
	.byte	$18
	.byte	$38
	.byte	$FD
	.byte	$02
	.byte	$80
_marathon_man__run5_data:
	.byte	$0B
	.byte	$16
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$03
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0B
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0B
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0B
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$22
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$21
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$32
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$31
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$42
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$41
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$51
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$52
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$62
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$61
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$60
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$72
	.byte	$02
	.byte	$00
	.byte	$38
	.byte	$71
	.byte	$02
	.byte	$80
_marathon_man__run6_data:
	.byte	$08
	.byte	$18
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$26
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$25
	.byte	$02
	.byte	$F8
	.byte	$10
	.byte	$24
	.byte	$02
	.byte	$F8
	.byte	$18
	.byte	$34
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$35
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$36
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$46
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$45
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$56
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$66
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$76
	.byte	$02
	.byte	$10
	.byte	$30
	.byte	$67
	.byte	$02
	.byte	$00
	.byte	$38
	.byte	$75
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$65
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$55
	.byte	$02
	.byte	$F8
	.byte	$28
	.byte	$54
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$64
	.byte	$02
	.byte	$F8
	.byte	$38
	.byte	$74
	.byte	$02
	.byte	$80
_marathon_man__walk1_data:
	.byte	$0B
	.byte	$16
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$0E
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$0D
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$1E
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$1D
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$2E
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$2D
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$3E
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$3D
	.byte	$02
	.byte	$F8
	.byte	$28
	.byte	$3C
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$4D
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$4C
	.byte	$02
	.byte	$F8
	.byte	$38
	.byte	$5C
	.byte	$02
	.byte	$00
	.byte	$38
	.byte	$5D
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$5E
	.byte	$02
	.byte	$10
	.byte	$38
	.byte	$5F
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$4E
	.byte	$02
	.byte	$80
_marathon_man__walk2_data:
	.byte	$08
	.byte	$19
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$03
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0B
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0B
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0B
	.byte	$17
	.byte	$02
	.byte	$07
	.byte	$10
	.byte	$6F
	.byte	$02
	.byte	$FF
	.byte	$10
	.byte	$6E
	.byte	$02
	.byte	$07
	.byte	$18
	.byte	$7F
	.byte	$02
	.byte	$FF
	.byte	$18
	.byte	$7E
	.byte	$02
	.byte	$07
	.byte	$20
	.byte	$8F
	.byte	$02
	.byte	$FF
	.byte	$20
	.byte	$8E
	.byte	$02
	.byte	$07
	.byte	$28
	.byte	$9F
	.byte	$02
	.byte	$FF
	.byte	$28
	.byte	$9E
	.byte	$02
	.byte	$07
	.byte	$30
	.byte	$AF
	.byte	$02
	.byte	$07
	.byte	$38
	.byte	$BF
	.byte	$02
	.byte	$FF
	.byte	$38
	.byte	$BE
	.byte	$02
	.byte	$FF
	.byte	$30
	.byte	$AE
	.byte	$02
	.byte	$F7
	.byte	$30
	.byte	$AD
	.byte	$02
	.byte	$F7
	.byte	$38
	.byte	$BD
	.byte	$02
	.byte	$80
_marathon_man__walk3_data:
	.byte	$06
	.byte	$19
	.byte	$08
	.byte	$00
	.byte	$0C
	.byte	$18
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$02
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$02
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0A
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0A
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$02
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$02
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0A
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0A
	.byte	$17
	.byte	$02
	.byte	$08
	.byte	$10
	.byte	$CF
	.byte	$02
	.byte	$00
	.byte	$10
	.byte	$CE
	.byte	$02
	.byte	$08
	.byte	$18
	.byte	$DF
	.byte	$02
	.byte	$00
	.byte	$18
	.byte	$DE
	.byte	$02
	.byte	$F8
	.byte	$18
	.byte	$DD
	.byte	$02
	.byte	$08
	.byte	$20
	.byte	$EF
	.byte	$02
	.byte	$00
	.byte	$20
	.byte	$EE
	.byte	$02
	.byte	$08
	.byte	$28
	.byte	$FF
	.byte	$02
	.byte	$00
	.byte	$28
	.byte	$FE
	.byte	$02
	.byte	$08
	.byte	$30
	.byte	$8C
	.byte	$02
	.byte	$08
	.byte	$38
	.byte	$9C
	.byte	$02
	.byte	$10
	.byte	$38
	.byte	$9D
	.byte	$02
	.byte	$00
	.byte	$30
	.byte	$8B
	.byte	$02
	.byte	$F8
	.byte	$30
	.byte	$8A
	.byte	$02
	.byte	$F8
	.byte	$38
	.byte	$9A
	.byte	$02
	.byte	$F8
	.byte	$10
	.byte	$CD
	.byte	$02
	.byte	$80
_marathon_man__walk4_data:
	.byte	$09
	.byte	$1A
	.byte	$08
	.byte	$00
	.byte	$FF
	.byte	$03
	.byte	$04
	.byte	$00
	.byte	$07
	.byte	$03
	.byte	$05
	.byte	$00
	.byte	$FF
	.byte	$0B
	.byte	$14
	.byte	$00
	.byte	$07
	.byte	$0B
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$03
	.byte	$06
	.byte	$02
	.byte	$08
	.byte	$03
	.byte	$07
	.byte	$02
	.byte	$00
	.byte	$0B
	.byte	$16
	.byte	$02
	.byte	$08
	.byte	$0B
	.byte	$17
	.byte	$02
	.byte	$07
	.byte	$10
	.byte	$88
	.byte	$02
	.byte	$FF
	.byte	$10
	.byte	$87
	.byte	$02
	.byte	$07
	.byte	$18
	.byte	$98
	.byte	$02
	.byte	$FF
	.byte	$18
	.byte	$97
	.byte	$02
	.byte	$07
	.byte	$20
	.byte	$A8
	.byte	$02
	.byte	$FF
	.byte	$20
	.byte	$A7
	.byte	$02
	.byte	$07
	.byte	$28
	.byte	$B8
	.byte	$02
	.byte	$FF
	.byte	$28
	.byte	$B7
	.byte	$02
	.byte	$FF
	.byte	$30
	.byte	$C7
	.byte	$02
	.byte	$07
	.byte	$30
	.byte	$C8
	.byte	$02
	.byte	$07
	.byte	$38
	.byte	$96
	.byte	$02
	.byte	$FF
	.byte	$38
	.byte	$95
	.byte	$02
	.byte	$F7
	.byte	$30
	.byte	$84
	.byte	$02
	.byte	$F7
	.byte	$38
	.byte	$94
	.byte	$02
	.byte	$80
_palette_sprites:
	.byte	$1B
	.byte	$26
	.byte	$07
	.byte	$21
	.byte	$1B
	.byte	$0C
	.byte	$21
	.byte	$32
	.byte	$1B
	.byte	$36
	.byte	$06
	.byte	$15
	.byte	$1B
	.byte	$27
	.byte	$16
	.byte	$29
_palette_bg:
	.byte	$0F
	.byte	$2D
	.byte	$1A
	.byte	$10
	.byte	$0F
	.byte	$11
	.byte	$1A
	.byte	$21
	.byte	$0F
	.byte	$2A
	.byte	$1A
	.byte	$0A
	.byte	$0F
	.byte	$17
	.byte	$1A
	.byte	$07
L087B:
	.byte	$20,$20,$53,$54,$45,$50,$53,$3A,$20,$00
L08BA:
	.byte	$20,$20,$54,$49,$4D,$45,$3A,$00
L090A:
	.byte	$20,$20,$53,$50,$4D,$3A,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_powerpad_cur:
	.res	2,$00
_powerpad_old:
	.res	2,$00
_powerpad_new:
	.res	2,$00
_debug_controller:
	.res	1,$00
_debug_controller_new:
	.res	1,$00
_temp_int:
	.res	2,$00
_last_step:
	.res	1,$00
_steps:
	.res	2,$00
_ones_step:
	.res	1,$00
_tens_step:
	.res	1,$00
_hundreds_step:
	.res	1,$00
_thousands_step:
	.res	1,$00
_ten_thousands_step:
	.res	1,$00
_steps_per_minute:
	.res	2,$00
_hundreds_spm:
	.res	1,$00
_tens_spm:
	.res	1,$00
_ones_spm:
	.res	1,$00
_seconds:
	.res	2,$00
_ones_seconds:
	.res	1,$00
_tens_seconds:
	.res	1,$00
_ones_minutes:
	.res	1,$00
_tens_minutes:
	.res	1,$00
_ones_hours:
	.res	1,$00
_tens_hours:
	.res	1,$00
_frame_counter:
	.res	1,$00
_step_button_lockout:
	.res	1,$00
_motion_counter:
	.res	1,$00
_time_since_button_press:
	.res	1,$00
_motion:
	.res	1,$00
_was_running:
	.res	1,$00
_was_walking:
	.res	1,$00
_mph:
	.res	1,$00
_sprite_timer:
	.res	1,$00
_sprite_frame_counter:
	.res	1,$00
_scroll_x:
	.res	2,$00
_largeindex:
	.res	2,$00
_scroll_timer:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ add_step (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_step: near

.segment	"CODE"

;
; if(step_button_lockout > 0){
;
	lda     _step_button_lockout
;
; return; //still in lockout period
;
	bne     L09A5
;
; sprite_timer = 0; //used for animation
;
	sta     _sprite_timer
;
; time_since_button_press = 0;
;
	sta     _time_since_button_press
;
; steps++;
;
	lda     _steps
	ldx     _steps+1
	clc
	adc     #$01
	bcc     L0986
	inx
L0986:	sta     _steps
	stx     _steps+1
;
; step_button_lockout = FRAMES_PER_STEP; //lock out for a few frames to avoid double counting
;
	lda     #$0A
	sta     _step_button_lockout
;
; if(ones_step == 9){
;
	lda     _ones_step
	cmp     #$09
	bne     L0ADC
;
; ones_step = 0;
;
	lda     #$00
	sta     _ones_step
;
; if(tens_step == 9){
;
	lda     _tens_step
	cmp     #$09
	bne     L0ADB
;
; tens_step = 0;
;
	lda     #$00
	sta     _tens_step
;
; if(hundreds_step == 9){
;
	lda     _hundreds_step
	cmp     #$09
	bne     L0ADA
;
; hundreds_step = 0;
;
	lda     #$00
	sta     _hundreds_step
;
; if(thousands_step == 9){
;
	lda     _thousands_step
	cmp     #$09
	bne     L0AD9
;
; thousands_step = 0;
;
	lda     #$00
	sta     _thousands_step
;
; if(ten_thousands_step == 9){
;
	lda     _ten_thousands_step
	cmp     #$09
	bne     L0AD8
;
; ten_thousands_step = 0;
;
	lda     #$00
	sta     _ten_thousands_step
;
; } else {
;
	rts
;
; ten_thousands_step++;
;
L0AD8:	inc     _ten_thousands_step
;
; } else {
;
	rts
;
; thousands_step++;
;
L0AD9:	inc     _thousands_step
;
; } else {
;
	rts
;
; hundreds_step++;
;
L0ADA:	inc     _hundreds_step
;
; } else {
;
	rts
;
; tens_step++;
;
L0ADB:	inc     _tens_step
;
; } else {
;
	rts
;
; ones_step++;
;
L0ADC:	inc     _ones_step
;
; }
;
L09A5:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ add_second (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_second: near

.segment	"CODE"

;
; seconds++;
;
	lda     _seconds
	ldx     _seconds+1
	clc
	adc     #$01
	bcc     L0959
	inx
L0959:	sta     _seconds
	stx     _seconds+1
;
; if(ones_seconds == 9){
;
	lda     _ones_seconds
	cmp     #$09
	bne     L0AE2
;
; ones_seconds = 0;
;
	lda     #$00
	sta     _ones_seconds
;
; if(tens_seconds == 5){
;
	lda     _tens_seconds
	cmp     #$05
	bne     L0AE1
;
; tens_seconds = 0;
;
	lda     #$00
	sta     _tens_seconds
;
; if(ones_minutes == 9){
;
	lda     _ones_minutes
	cmp     #$09
	bne     L0AE0
;
; ones_minutes = 0;
;
	lda     #$00
	sta     _ones_minutes
;
; if(tens_minutes == 5){
;
	lda     _tens_minutes
	cmp     #$05
	bne     L0ADF
;
; tens_minutes = 0;
;
	lda     #$00
	sta     _tens_minutes
;
; if(ones_hours == 9){
;
	lda     _ones_hours
	cmp     #$09
	bne     L0ADE
;
; ones_hours = 0;
;
	lda     #$00
	sta     _ones_hours
;
; if(tens_hours == 2){
;
	lda     _tens_hours
	cmp     #$02
	bne     L0ADD
;
; tens_hours = 0;
;
	lda     #$00
	sta     _tens_hours
;
; } else {
;
	rts
;
; tens_hours++;
;
L0ADD:	inc     _tens_hours
;
; } else {
;
	rts
;
; ones_hours++;
;
L0ADE:	inc     _ones_hours
;
; } else {
;
	rts
;
; tens_minutes++;
;
L0ADF:	inc     _tens_minutes
;
; } else {
;
	rts
;
; ones_minutes++;
;
L0AE0:	inc     _ones_minutes
;
; } else {
;
	rts
;
; tens_seconds++;
;
L0AE1:	inc     _tens_seconds
;
; } else {
;
	rts
;
; ones_seconds++;
;
L0AE2:	inc     _ones_seconds
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ initial_steps_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_steps_conversion: near

.segment	"CODE"

;
; temp_int = steps;
;
	lda     _steps
	ldx     _steps+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _tens_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; hundreds_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _hundreds_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _thousands_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ten_thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ initial_timer_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_timer_conversion: near

.segment	"CODE"

;
; temp_int = seconds;
;
	lda     _seconds
	ldx     _seconds+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_seconds = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_seconds
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_seconds = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_seconds
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_minutes = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_minutes
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_minutes = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_minutes
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_hours = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_hours
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_hours = temp_int % 3;
;
	jsr     pushax
	lda     #$03
	jsr     tosumoda0
	sta     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ check_motion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_motion: near

.segment	"CODE"

;
; if((powerpad_cur & 0x0F) && (powerpad_cur & 0xF0) && time_since_button_press < 180){
;
	lda     _powerpad_cur
	and     #$0F
	beq     L09A8
	lda     _powerpad_cur
	and     #$F0
	beq     L09A8
	lda     _time_since_button_press
	cmp     #$B4
	bcs     L09A8
;
; was_walking = 1;
;
	lda     #$01
	sta     _was_walking
;
; }else if(powerpad_cur == 0 && time_since_button_press < 60){ //nothing is pressed
;
	rts
L09A8:	lda     _powerpad_cur
	ora     _powerpad_cur+1
	bne     L0AE6
	lda     _time_since_button_press
	cmp     #$3C
	bcc     L0AE7
L0AE6:	rts
;
; was_running = 1;
;
L0AE7:	lda     #$01
	sta     _was_running
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_motion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_motion: near

.segment	"CODE"

;
; if(was_running){
;
	lda     _was_running
	beq     L09BA
;
; motion = RUNNING;
;
	lda     #$00
	sta     _motion
;
; motion_counter = MOTION_HOLD_FRAMES;
;
	lda     #$B4
	sta     _motion_counter
;
; else if(was_walking){
;
	jmp     L0AE8
L09BA:	lda     _was_walking
	beq     L09C1
;
; motion = WALKING;
;
	lda     #$01
	sta     _motion
;
; motion_counter = MOTION_HOLD_FRAMES;
;
	lda     #$B4
	sta     _motion_counter
;
; else {
;
	jmp     L0AE8
;
; motion = STANDING;
;
L09C1:	lda     #$02
	sta     _motion
;
; was_walking = 0;
;
L0AE8:	lda     #$00
	sta     _was_walking
;
; was_running = 0;
;
	sta     _was_running
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ load_room (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_room: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (largeindex = 0; largeindex < 1024; ++largeindex)
;
	lda     #$00
	sta     _largeindex
	sta     _largeindex+1
L0AB9:	ldx     _largeindex+1
	cpx     #$04
	bcs     L0ABA
;
; vram_put(track[largeindex]);
;
	lda     #<(_track)
	sta     ptr1
	lda     #>(_track)
	clc
	adc     _largeindex+1
	sta     ptr1+1
	ldy     _largeindex
	lda     (ptr1),y
	jsr     _vram_put
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; for (largeindex = 0; largeindex < 1024; ++largeindex)
;
	inc     _largeindex
	bne     L0AB9
	inc     _largeindex+1
	jmp     L0AB9
;
; vram_adr(NTADR_A(15,13));
;
L0ABA:	ldx     #$21
	lda     #$AF
	jsr     _vram_adr
;
; vram_put(0x69);
;
	lda     #$69
	jsr     _vram_put
;
; ppu_on_all();
;
	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ draw_sprite (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_sprite: near

.segment	"CODE"

;
; oam_clear();
;
	jsr     _oam_clear
;
; set_sprite_zero();
;
	jsr     _set_sprite_zero
;
; oam_set(4); // start drawing from slot 4
;
	lda     #$04
	jsr     _oam_set
;
; ++sprite_frame_counter;
;
	inc     _sprite_frame_counter
;
; if(sprite_frame_counter <10){
;
	lda     _sprite_frame_counter
	cmp     #$0A
	bcs     L0AE9
;
; oam_meta_spr(120, 120, marathon_man__run1_data); 
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run1_data)
	ldx     #>(_marathon_man__run1_data)
	jmp     _oam_meta_spr
;
; } else if (sprite_frame_counter <20){
;
L0AE9:	lda     _sprite_frame_counter
	cmp     #$14
	bcs     L0AEA
;
; oam_meta_spr(120, 120, marathon_man__run2_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run2_data)
	ldx     #>(_marathon_man__run2_data)
	jmp     _oam_meta_spr
;
; } else if (sprite_frame_counter <30){
;
L0AEA:	lda     _sprite_frame_counter
	cmp     #$1E
	bcs     L0AEB
;
; oam_meta_spr(120, 120, marathon_man__run3_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run3_data)
	ldx     #>(_marathon_man__run3_data)
	jmp     _oam_meta_spr
;
; } else if (sprite_frame_counter <40){
;
L0AEB:	lda     _sprite_frame_counter
	cmp     #$28
	bcs     L0AEC
;
; oam_meta_spr(120, 120, marathon_man__run4_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run4_data)
	ldx     #>(_marathon_man__run4_data)
	jmp     _oam_meta_spr
;
; } else if (sprite_frame_counter <50){
;
L0AEC:	lda     _sprite_frame_counter
	cmp     #$32
	bcs     L0AED
;
; oam_meta_spr(120, 120, marathon_man__run5_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run5_data)
	ldx     #>(_marathon_man__run5_data)
	jmp     _oam_meta_spr
;
; } else if (sprite_frame_counter < 59){
;
L0AED:	lda     _sprite_frame_counter
	cmp     #$3B
	bcs     L0AEE
;
; oam_meta_spr(120, 120, marathon_man__run6_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run6_data)
	ldx     #>(_marathon_man__run6_data)
	jmp     _oam_meta_spr
;
; sprite_frame_counter = 0;
;
L0AEE:	lda     #$00
	sta     _sprite_frame_counter
;
; oam_meta_spr(120, 120, marathon_man__run6_data);
;
	jsr     decsp2
	lda     #$78
	ldy     #$01
	sta     (sp),y
	dey
	sta     (sp),y
	lda     #<(_marathon_man__run6_data)
	ldx     #>(_marathon_man__run6_data)
	jmp     _oam_meta_spr

.endproc

; ---------------------------------------------------------------
; void __near__ draw_hud (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_hud: near

.segment	"CODE"

;
; multi_vram_buffer_horz("  STEPS: ", 9, NTADR_A(1, 4));
;
	jsr     decsp3
	lda     #<(L087B)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L087B)
	sta     (sp),y
	lda     #$09
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$81
	jsr     _multi_vram_buffer_horz
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	lda     _ten_thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; one_vram_buffer(',', NTADR_A(12, 4));
;
	lda     #$2C
	jsr     pusha
	ldx     #$20
	lda     #$8C
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jsr     _one_vram_buffer
;
; multi_vram_buffer_horz("  TIME:", 7, NTADR_A(1, 2));
;
	jsr     decsp3
	lda     #<(L08BA)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L08BA)
	sta     (sp),y
	lda     #$07
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$41
	jsr     _multi_vram_buffer_horz
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	lda     _tens_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; one_vram_buffer(':', NTADR_A(10, 2));
;
	lda     #$3A
	jsr     pusha
	ldx     #$20
	lda     #$4A
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; one_vram_buffer(':', NTADR_A(13, 2));
;
	lda     #$3A
	jsr     pusha
	ldx     #$20
	lda     #$4D
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jsr     _one_vram_buffer
;
; multi_vram_buffer_horz("  SPM:", 6, NTADR_A(1, 6));
;
	jsr     decsp3
	lda     #<(L090A)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L090A)
	sta     (sp),y
	lda     #$06
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$C1
	jsr     _multi_vram_buffer_horz
;
; one_vram_buffer(0x30+hundreds_spm, NTADR_A(13, 6));
;
	lda     _hundreds_spm
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$CD
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_spm, NTADR_A(14, 6));
;
	lda     _tens_spm
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$CE
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_spm, NTADR_A(15, 6));
;
	lda     _ones_spm
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$CF
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ process_controller (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_process_controller: near

.segment	"CODE"

;
; if(debug_controller_new & PAD_A || debug_controller_new & PAD_B){
;
	lda     _debug_controller_new
	and     #$80
	bne     L0AEF
	lda     _debug_controller_new
	and     #$40
	beq     L092F
;
; add_step();
;
L0AEF:	jsr     _add_step
;
; if(powerpad_new & POWERPAD_1){
;
L092F:	lda     _powerpad_new+1
	and     #$10
	beq     L0933
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_2){
;
L0933:	lda     _powerpad_new+1
	and     #$40
	beq     L0936
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_3){
;
L0936:	lda     _powerpad_new+1
	and     #$20
	beq     L0939
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_4){
;
L0939:	lda     _powerpad_new+1
	and     #$80
	beq     L093C
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_5){
;
L093C:	lda     _powerpad_new+1
	and     #$04
	beq     L093F
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_6){
;
L093F:	lda     _powerpad_new
	and     #$40
	beq     L0942
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_7){
;
L0942:	lda     _powerpad_new
	and     #$01
	beq     L0945
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_8){
;
L0945:	lda     _powerpad_new+1
	and     #$02
	beq     L0948
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_9){
;
L0948:	lda     _powerpad_new+1
	and     #$01
	beq     L094B
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_10){
;
L094B:	lda     _powerpad_new
	and     #$10
	beq     L094E
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_11){
;
L094E:	lda     _powerpad_new
	and     #$04
	beq     L0951
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_12){
;
L0951:	lda     _powerpad_new+1
	and     #$08
;
; add_step();
;
	jne     _add_step
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ set_sprite_zero (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_sprite_zero: near

.segment	"CODE"

;
; oam_set(0); // double check that this goes in the zero slot
;
	lda     #$00
	jsr     _oam_set
;
; oam_spr(0x78,104,0x69,3); // x=120, y=104, tile=105, attr=3
;
	jsr     decsp3
	lda     #$78
	ldy     #$02
	sta     (sp),y
	lda     #$68
	dey
	sta     (sp),y
	lda     #$69
	dey
	sta     (sp),y
	lda     #$03
	jmp     _oam_spr

.endproc

; ---------------------------------------------------------------
; void __near__ update_steps_per_minute (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_steps_per_minute: near

.segment	"CODE"

;
; if(seconds == 0){
;
	jsr     decsp2
	lda     _seconds
	ora     _seconds+1
	bne     L0A60
;
; steps_per_minute = 0;
;
	tax
;
; } else {
;
	jmp     L0AF1
;
; elapsed_minutes = seconds / 60;
;
L0A60:	lda     _seconds
	ldx     _seconds+1
	jsr     pushax
	lda     #$3C
	jsr     tosudiva0
	jsr     stax0sp
;
; if(elapsed_minutes == 0){
;
	cpx     #$00
	bne     L0A68
	cmp     #$00
	bne     L0A68
;
; elapsed_minutes = 1;
;
	tay
	lda     #$01
	sta     (sp),y
	txa
	iny
	sta     (sp),y
;
; steps_per_minute = steps / elapsed_minutes;
;
L0A68:	lda     _steps
	ldx     _steps+1
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	jsr     tosudivax
L0AF1:	sta     _steps_per_minute
	stx     _steps_per_minute+1
;
; if(steps_per_minute > 999){
;
	lda     _steps_per_minute
	cmp     #$E8
	lda     _steps_per_minute+1
	sbc     #$03
	bcc     L0A6F
;
; steps_per_minute = 999;
;
	ldx     #$03
	lda     #$E7
	sta     _steps_per_minute
	stx     _steps_per_minute+1
;
; temp_int = steps_per_minute;
;
L0A6F:	lda     _steps_per_minute
	ldx     _steps_per_minute+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_spm = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_spm
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_spm = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _tens_spm
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; hundreds_spm = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _hundreds_spm
;
; }
;
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ process_powerpad (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_process_powerpad: near

.segment	"CODE"

;
; powerpad_new = (powerpad_cur^powerpad_old)&powerpad_cur;
;
	lda     _powerpad_old
	eor     _powerpad_cur
	sta     ptr1
	lda     _powerpad_old+1
	eor     _powerpad_cur+1
	sta     ptr1+1
	lda     _powerpad_cur
	and     ptr1
	sta     _powerpad_new
	lda     _powerpad_cur+1
	and     ptr1+1
	sta     _powerpad_new+1
;
; powerpad_old = powerpad_cur;
;
	lda     _powerpad_cur+1
	sta     _powerpad_old+1
	lda     _powerpad_cur
	sta     _powerpad_old
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; clear_vram_buffer(); 
;
	jsr     _clear_vram_buffer
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; set_scroll_y(0xff); // shift the bg down one pixel
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_bg); 
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_sprites);
;
	lda     #<(_palette_sprites)
	ldx     #>(_palette_sprites)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; load_room();
;
	jsr     _load_room
;
; set_sprite_zero(); // this needs to be done before ppu_on_all, to make sure the sprite zero is in place for the split
;
	jsr     _set_sprite_zero
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; steps = 0;
;
	lda     #$00
	sta     _steps
	sta     _steps+1
;
; seconds = 0;
;
	sta     _seconds
	sta     _seconds+1
;
; steps_per_minute = 0;
;
	sta     _steps_per_minute
	sta     _steps_per_minute+1
;
; initial_steps_conversion();
;
	jsr     _initial_steps_conversion
;
; initial_timer_conversion();
;
	jsr     _initial_timer_conversion
;
; update_steps_per_minute();
;
	jsr     _update_steps_per_minute
;
; motion = STANDING;
;
	lda     #$02
	sta     _motion
;
; motion_counter = 0;
;
	lda     #$00
	sta     _motion_counter
;
; ppu_wait_nmi(); // wait till beginning of the frame
;
L0845:	jsr     _ppu_wait_nmi
;
; set_sprite_zero();
;
	jsr     _set_sprite_zero
;
; split(scroll_x);
;
	lda     _scroll_x
	ldx     _scroll_x+1
	jsr     _split
;
; set_scroll_x(0);
;
	ldx     #$00
	txa
	jsr     _set_scroll_x
;
; set_scroll_y(0xff);
;
	ldx     #$00
	lda     #$FF
	jsr     _set_scroll_y
;
; ++frame_counter;
;
	inc     _frame_counter
;
; ++scroll_timer;
;
	inc     _scroll_timer
;
; if(time_since_button_press < 255){
;
	lda     _time_since_button_press
	cmp     #$FF
	bcs     L0AF2
;
; ++time_since_button_press;
;
	inc     _time_since_button_press
;
; if(scroll_timer >= 8){
;
L0AF2:	lda     _scroll_timer
	cmp     #$08
	bcc     L0AF3
;
; scroll_timer = 0;
;
	lda     #$00
	sta     _scroll_timer
;
; ++scroll_x ; //debug no scrolling
;
	inc     _scroll_x
	bne     L0AF3
	inc     _scroll_x+1
;
; if(step_button_lockout > 0){
;
L0AF3:	lda     _step_button_lockout
	beq     L0AF4
;
; --step_button_lockout;
;
	dec     _step_button_lockout
;
; if(motion_counter > 0){
;
L0AF4:	lda     _motion_counter
	beq     L0AF5
;
; --motion_counter;
;
	dec     _motion_counter
;
; if(frame_counter >= 60){
;
L0AF5:	lda     _frame_counter
	cmp     #$3C
	lda     #$00
	bcc     L0AF6
;
; frame_counter = 0;
;
	sta     _frame_counter
;
; add_second();
;
	jsr     _add_second
;
; update_steps_per_minute();
;
	jsr     _update_steps_per_minute
;
; debug_controller = pad_poll(0); //for debugging only
;
	lda     #$00
L0AF6:	jsr     _pad_poll
	sta     _debug_controller
;
; debug_controller_new = get_pad_new(0);  
;
	lda     #$00
	jsr     _get_pad_new
	sta     _debug_controller_new
;
; powerpad_cur = read_powerpad(1);
;
	lda     #$01
	jsr     _read_powerpad
	sta     _powerpad_cur
	stx     _powerpad_cur+1
;
; process_powerpad(); // goes after the read
;
	jsr     _process_powerpad
;
; check_motion();
;
	jsr     _check_motion
;
; if(motion_counter == 0){
;
	lda     _motion_counter
	bne     L0873
;
; update_motion();
;
	jsr     _update_motion
;
; draw_sprite();
;
L0873:	jsr     _draw_sprite
;
; draw_hud();
;
	jsr     _draw_hud
;
; process_controller();
;
	jsr     _process_controller
;
; while (1){
;
	jmp     L0845

.endproc

