;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_spr
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_unrle
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_clear_vram_buffer
	.import		_read_powerpad
	.export		_PowerBG
	.export		_powerpad_cur
	.export		_powerpad_old
	.export		_powerpad_new
	.export		_temp_int
	.export		_last_step
	.export		_steps
	.export		_ones_step
	.export		_tens_step
	.export		_hundreds_step
	.export		_thousands_step
	.export		_ten_thousands_step
	.export		_seconds
	.export		_ones_seconds
	.export		_tens_seconds
	.export		_ones_minutes
	.export		_tens_minutes
	.export		_ones_hours
	.export		_tens_hours
	.export		_frame_counter
	.export		_add_step
	.export		_add_second
	.export		_initial_steps_conversion
	.export		_initial_timer_conversion
	.export		_pal1
	.export		_pal2
	.export		_process_powerpad
	.export		_main

.segment	"RODATA"

_PowerBG:
	.byte	$01
	.byte	$00
	.byte	$01
	.byte	$41
	.byte	$50
	.byte	$6F
	.byte	$77
	.byte	$65
	.byte	$72
	.byte	$70
	.byte	$61
	.byte	$64
	.byte	$00
	.byte	$00
	.byte	$54
	.byte	$65
	.byte	$73
	.byte	$74
	.byte	$00
	.byte	$01
	.byte	$31
	.byte	$50
	.byte	$6F
	.byte	$72
	.byte	$74
	.byte	$00
	.byte	$32
	.byte	$00
	.byte	$01
	.byte	$63
	.byte	$A7
	.byte	$A8
	.byte	$A8
	.byte	$A9
	.byte	$00
	.byte	$01
	.byte	$18
	.byte	$90
	.byte	$91
	.byte	$91
	.byte	$97
	.byte	$98
	.byte	$98
	.byte	$99
	.byte	$91
	.byte	$91
	.byte	$92
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$91
	.byte	$01
	.byte	$09
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$96
	.byte	$A0
	.byte	$A1
	.byte	$A0
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A2
	.byte	$A3
	.byte	$96
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$91
	.byte	$B0
	.byte	$B1
	.byte	$B0
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B2
	.byte	$B3
	.byte	$91
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$95
	.byte	$01
	.byte	$09
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$96
	.byte	$A0
	.byte	$A1
	.byte	$A0
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A2
	.byte	$A3
	.byte	$96
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$91
	.byte	$B0
	.byte	$B1
	.byte	$B0
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B2
	.byte	$B3
	.byte	$91
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$95
	.byte	$01
	.byte	$09
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$96
	.byte	$A0
	.byte	$A1
	.byte	$A0
	.byte	$A1
	.byte	$A2
	.byte	$A3
	.byte	$A2
	.byte	$A3
	.byte	$96
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$91
	.byte	$B0
	.byte	$B1
	.byte	$B0
	.byte	$B1
	.byte	$B2
	.byte	$B3
	.byte	$B2
	.byte	$B3
	.byte	$91
	.byte	$00
	.byte	$01
	.byte	$15
	.byte	$93
	.byte	$91
	.byte	$01
	.byte	$07
	.byte	$94
	.byte	$00
	.byte	$01
	.byte	$FE
	.byte	$00
	.byte	$01
	.byte	$78
	.byte	$50
	.byte	$00
	.byte	$01
	.byte	$06
	.byte	$05
	.byte	$00
	.byte	$01
	.byte	$2A
	.byte	$00
	.byte	$01
	.byte	$00
_pal1:
	.byte	$0F
	.byte	$11
	.byte	$16
	.byte	$30
	.byte	$0F
	.byte	$00
	.byte	$10
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_pal2:
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
L00EA:
	.byte	$54,$49,$4D,$45,$3A,$20,$30,$30,$3A,$30,$30,$3A,$30,$30,$00
L00E0:
	.byte	$53,$54,$45,$50,$53,$3A,$20,$20,$30,$30,$2C,$30,$30,$30,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_powerpad_cur:
	.res	2,$00
_powerpad_old:
	.res	2,$00
_powerpad_new:
	.res	2,$00
_temp_int:
	.res	2,$00
_last_step:
	.res	1,$00
_steps:
	.res	2,$00
_ones_step:
	.res	1,$00
_tens_step:
	.res	1,$00
_hundreds_step:
	.res	1,$00
_thousands_step:
	.res	1,$00
_ten_thousands_step:
	.res	1,$00
_seconds:
	.res	2,$00
_ones_seconds:
	.res	1,$00
_tens_seconds:
	.res	1,$00
_ones_minutes:
	.res	1,$00
_tens_minutes:
	.res	1,$00
_ones_hours:
	.res	1,$00
_tens_hours:
	.res	1,$00
_frame_counter:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ add_step (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_step: near

.segment	"CODE"

;
; steps++;
;
	lda     _steps
	ldx     _steps+1
	clc
	adc     #$01
	bcc     L01FF
	inx
L01FF:	sta     _steps
	stx     _steps+1
;
; if(ones_step == 9){
;
	lda     _ones_step
	cmp     #$09
	jne     L0310
;
; ones_step = 0;
;
	lda     #$00
	sta     _ones_step
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jsr     _one_vram_buffer
;
; if(tens_step == 9){
;
	lda     _tens_step
	cmp     #$09
	jne     L030F
;
; tens_step = 0;
;
	lda     #$00
	sta     _tens_step
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; if(hundreds_step == 9){
;
	lda     _hundreds_step
	cmp     #$09
	bne     L030E
;
; hundreds_step = 0;
;
	lda     #$00
	sta     _hundreds_step
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; if(thousands_step == 9){
;
	lda     _thousands_step
	cmp     #$09
	bne     L030D
;
; thousands_step = 0;
;
	lda     #$00
	sta     _thousands_step
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; if(ten_thousands_step == 9){
;
	lda     _ten_thousands_step
	cmp     #$09
	bne     L030C
;
; ten_thousands_step = 0;
;
	lda     #$00
	sta     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
;
; } else {
;
	jmp     _one_vram_buffer
;
; ten_thousands_step++;
;
L030C:	inc     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	lda     _ten_thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
;
; } else {
;
	jmp     _one_vram_buffer
;
; thousands_step++;
;
L030D:	inc     _thousands_step
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
;
; } else {
;
	jmp     _one_vram_buffer
;
; hundreds_step++;
;
L030E:	inc     _hundreds_step
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jmp     _one_vram_buffer
;
; tens_step++;
;
L030F:	inc     _tens_step
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jmp     _one_vram_buffer
;
; ones_step++;
;
L0310:	inc     _ones_step
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ add_second (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_second: near

.segment	"CODE"

;
; seconds++;
;
	lda     _seconds
	ldx     _seconds+1
	clc
	adc     #$01
	bcc     L016C
	inx
L016C:	sta     _seconds
	stx     _seconds+1
;
; if(ones_seconds == 9){
;
	lda     _ones_seconds
	cmp     #$09
	jne     L031A
;
; ones_seconds = 0;
;
	lda     #$00
	sta     _ones_seconds
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jsr     _one_vram_buffer
;
; if(tens_seconds == 5){
;
	lda     _tens_seconds
	cmp     #$05
	jne     L0319
;
; tens_seconds = 0;
;
	lda     #$00
	sta     _tens_seconds
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; if(ones_minutes == 9){
;
	lda     _ones_minutes
	cmp     #$09
	jne     L0318
;
; ones_minutes = 0;
;
	lda     #$00
	sta     _ones_minutes
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; if(tens_minutes == 5){
;
	lda     _tens_minutes
	cmp     #$05
	bne     L0317
;
; tens_minutes = 0;
;
	lda     #$00
	sta     _tens_minutes
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; if(ones_hours == 9){
;
	lda     _ones_hours
	cmp     #$09
	bne     L0316
;
; ones_hours = 0;
;
	lda     #$00
	sta     _ones_hours
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; if(tens_hours == 2){
;
	lda     _tens_hours
	cmp     #$02
	bne     L0315
;
; tens_hours = 0;
;
	lda     #$00
	sta     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
;
; } else {
;
	jmp     _one_vram_buffer
;
; tens_hours++;
;
L0315:	inc     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	lda     _tens_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
;
; } else {
;
	jmp     _one_vram_buffer
;
; ones_hours++;
;
L0316:	inc     _ones_hours
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
;
; } else {
;
	jmp     _one_vram_buffer
;
; tens_minutes++;
;
L0317:	inc     _tens_minutes
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
;
; } else {
;
	jmp     _one_vram_buffer
;
; ones_minutes++;
;
L0318:	inc     _ones_minutes
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jmp     _one_vram_buffer
;
; tens_seconds++;
;
L0319:	inc     _tens_seconds
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jmp     _one_vram_buffer
;
; ones_seconds++;
;
L031A:	inc     _ones_seconds
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ initial_steps_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_steps_conversion: near

.segment	"CODE"

;
; temp_int = steps;
;
	lda     _steps
	ldx     _steps+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _tens_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; hundreds_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _hundreds_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _thousands_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ten_thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ initial_timer_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_timer_conversion: near

.segment	"CODE"

;
; temp_int = seconds;
;
	lda     _seconds
	ldx     _seconds+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_seconds = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_seconds
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_seconds = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_seconds
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_minutes = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_minutes
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_minutes = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_minutes
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_hours = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_hours
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_hours = temp_int % 3;
;
	jsr     pushax
	lda     #$03
	jsr     tosumoda0
	sta     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ process_powerpad (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_process_powerpad: near

.segment	"CODE"

;
; powerpad_new = (powerpad_cur^powerpad_old)&powerpad_cur;
;
	lda     _powerpad_old
	eor     _powerpad_cur
	sta     ptr1
	lda     _powerpad_old+1
	eor     _powerpad_cur+1
	sta     ptr1+1
	lda     _powerpad_cur
	and     ptr1
	sta     _powerpad_new
	lda     _powerpad_cur+1
	and     ptr1+1
	sta     _powerpad_new+1
;
; powerpad_old = powerpad_cur;
;
	lda     _powerpad_cur+1
	sta     _powerpad_old+1
	lda     _powerpad_cur
	sta     _powerpad_old
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(pal1);
;
	lda     #<(_pal1)
	ldx     #>(_pal1)
	jsr     _pal_bg
;
; pal_spr(pal2);
;
	lda     #<(_pal2)
	ldx     #>(_pal2)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; vram_adr(NAMETABLE_A); // set a start position for the text
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; vram_unrle(PowerBG);
;
	lda     #<(_PowerBG)
	ldx     #>(_PowerBG)
	jsr     _vram_unrle
;
; clear_vram_buffer();
;
	jsr     _clear_vram_buffer
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; multi_vram_buffer_horz("STEPS:  00,000", 14, NTADR_A(2, 4));
;
	jsr     decsp3
	lda     #<(L00E0)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L00E0)
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$82
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("TIME: 00:00:00", 14, NTADR_A(2, 2));
;
	jsr     decsp3
	lda     #<(L00EA)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L00EA)
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$42
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; steps = 1232;
;
	ldx     #$04
	lda     #$D0
	sta     _steps
	stx     _steps+1
;
; seconds = 521;
;
	ldx     #$02
	lda     #$09
	sta     _seconds
	stx     _seconds+1
;
; initial_steps_conversion();
;
	jsr     _initial_steps_conversion
;
; initial_timer_conversion();
;
	jsr     _initial_timer_conversion
;
; ppu_wait_nmi(); // wait till beginning of the frame
;
L00FA:	jsr     _ppu_wait_nmi
;
; ++frame_counter;
;
	inc     _frame_counter
;
; if(frame_counter >= 60){
;
	lda     _frame_counter
	cmp     #$3C
	bcc     L0100
;
; frame_counter = 0;
;
	lda     #$00
	sta     _frame_counter
;
; add_second();
;
	jsr     _add_second
;
; oam_clear();
;
L0100:	jsr     _oam_clear
;
; powerpad_cur = read_powerpad(1);
;
	lda     #$01
	jsr     _read_powerpad
	sta     _powerpad_cur
	stx     _powerpad_cur+1
;
; process_powerpad(); // goes after the read
;
	jsr     _process_powerpad
;
; if(powerpad_new & POWERPAD_1){
;
	lda     _powerpad_new+1
	and     #$10
	beq     L010A
;
; oam_spr(84, 83, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_2){
;
L010A:	lda     _powerpad_new+1
	and     #$40
	beq     L0112
;
; oam_spr(100, 83, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_3){
;
L0112:	lda     _powerpad_new+1
	and     #$20
	beq     L011A
;
; oam_spr(116, 83, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_4){
;
L011A:	lda     _powerpad_new+1
	and     #$80
	beq     L0122
;
; oam_spr(132, 83, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_5){
;
L0122:	lda     _powerpad_new+1
	and     #$04
	beq     L012A
;
; oam_spr(84, 107, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_6){
;
L012A:	lda     _powerpad_new
	and     #$40
	beq     L0132
;
; oam_spr(100, 107, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_7){
;
L0132:	lda     _powerpad_new
	and     #$01
	beq     L013A
;
; oam_spr(116, 107, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_8){
;
L013A:	lda     _powerpad_new+1
	and     #$02
	beq     L0142
;
; oam_spr(132, 107, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_9){
;
L0142:	lda     _powerpad_new+1
	and     #$01
	beq     L014A
;
; oam_spr(84, 131, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_10){
;
L014A:	lda     _powerpad_new
	and     #$10
	beq     L0152
;
; oam_spr(100, 131, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_11){
;
L0152:	lda     _powerpad_new
	and     #$04
	beq     L015A
;
; oam_spr(116, 131, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_12){
;
L015A:	lda     _powerpad_new+1
	and     #$08
	jeq     L00FA
;
; oam_spr(132, 131, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; while (1){
;
	jmp     L00FA

.endproc

