;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_ppu_on_all
	.import		_oam_clear
	.import		_oam_spr
	.import		_bank_spr
	.import		_vram_adr
	.import		_vram_put
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.import		_multi_vram_buffer_horz
	.import		_clear_vram_buffer
	.import		_flush_vram_update2
	.import		_read_powerpad
	.export		_powerpad_cur
	.export		_powerpad_old
	.export		_powerpad_new
	.export		_temp_int
	.export		_last_step
	.export		_steps
	.export		_ones_step
	.export		_tens_step
	.export		_hundreds_step
	.export		_thousands_step
	.export		_ten_thousands_step
	.export		_seconds
	.export		_ones_seconds
	.export		_tens_seconds
	.export		_ones_minutes
	.export		_tens_minutes
	.export		_ones_hours
	.export		_tens_hours
	.export		_frame_counter
	.export		_step_button_lockout
	.export		_motion_counter
	.export		_time_since_button_press
	.export		_motion
	.export		_was_running
	.export		_was_walking
	.export		_largeindex
	.export		_add_step
	.export		_add_second
	.export		_initial_steps_conversion
	.export		_initial_timer_conversion
	.export		_check_motion
	.export		_update_motion
	.export		_load_room
	.export		_Track
	.export		_process_powerpad
	.export		_palette_sprites
	.export		_palette_bg
	.export		_main

.segment	"RODATA"

_Track:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$6B
	.byte	$69
	.byte	$6A
	.byte	$02
	.byte	$63
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$63
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$62
	.byte	$03
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$95
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$62
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$62
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$91
	.byte	$92
	.byte	$93
	.byte	$94
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$63
	.byte	$02
	.byte	$02
	.byte	$62
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$61
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$62
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$A1
	.byte	$A2
	.byte	$03
	.byte	$03
	.byte	$62
	.byte	$62
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$62
	.byte	$03
	.byte	$03
	.byte	$61
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$63
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$03
	.byte	$03
	.byte	$63
	.byte	$02
	.byte	$B1
	.byte	$B2
	.byte	$03
	.byte	$03
	.byte	$02
	.byte	$02
	.byte	$61
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$02
	.byte	$62
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$60
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$85
	.byte	$75
	.byte	$75
	.byte	$85
	.byte	$73
	.byte	$73
	.byte	$75
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$75
	.byte	$75
	.byte	$83
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$83
	.byte	$75
	.byte	$75
	.byte	$83
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$75
	.byte	$85
	.byte	$74
	.byte	$75
	.byte	$73
	.byte	$75
	.byte	$73
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$83
	.byte	$73
	.byte	$83
	.byte	$84
	.byte	$85
	.byte	$75
	.byte	$74
	.byte	$85
	.byte	$85
	.byte	$73
	.byte	$73
	.byte	$73
	.byte	$74
	.byte	$73
	.byte	$73
	.byte	$73
	.byte	$75
	.byte	$85
	.byte	$85
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$85
	.byte	$73
	.byte	$75
	.byte	$75
	.byte	$85
	.byte	$85
	.byte	$73
	.byte	$74
	.byte	$73
	.byte	$85
	.byte	$85
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$83
	.byte	$73
	.byte	$75
	.byte	$75
	.byte	$73
	.byte	$73
	.byte	$85
	.byte	$73
	.byte	$73
	.byte	$83
	.byte	$83
	.byte	$75
	.byte	$73
	.byte	$83
	.byte	$75
	.byte	$74
	.byte	$75
	.byte	$75
	.byte	$85
	.byte	$83
	.byte	$83
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$82
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$82
	.byte	$71
	.byte	$82
	.byte	$82
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$82
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$82
	.byte	$71
	.byte	$72
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$81
	.byte	$82
	.byte	$71
	.byte	$71
	.byte	$71
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$03
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$78
	.byte	$76
	.byte	$77
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$30
	.byte	$00
	.byte	$FF
	.byte	$FF
	.byte	$BF
	.byte	$BF
	.byte	$BF
	.byte	$AF
	.byte	$EF
	.byte	$BF
	.byte	$AB
	.byte	$AB
	.byte	$AB
	.byte	$AE
	.byte	$AE
	.byte	$AA
	.byte	$AF
	.byte	$AF
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$AA
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$0F
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_palette_sprites:
	.byte	$1B
	.byte	$26
	.byte	$07
	.byte	$21
	.byte	$1B
	.byte	$0C
	.byte	$21
	.byte	$32
	.byte	$1B
	.byte	$36
	.byte	$06
	.byte	$15
	.byte	$1B
	.byte	$27
	.byte	$16
	.byte	$29
_palette_bg:
	.byte	$0F
	.byte	$30
	.byte	$07
	.byte	$21
	.byte	$0F
	.byte	$00
	.byte	$19
	.byte	$10
	.byte	$0F
	.byte	$17
	.byte	$06
	.byte	$19
	.byte	$0F
	.byte	$29
	.byte	$19
	.byte	$09
L0436:
	.byte	$53,$54,$45,$50,$53,$3A,$20,$20,$30,$30,$2C,$30,$30,$30,$00
L0440:
	.byte	$54,$49,$4D,$45,$3A,$20,$30,$30,$3A,$30,$30,$3A,$30,$30,$00
L0626:
	.byte	$52,$55,$4E,$20,$20,$00
L0632:
	.byte	$53,$54,$41,$4E,$44,$00
L0455	:=	L0632+0
L061A:
	.byte	$57,$41,$4C,$4B,$20,$00

.segment	"BSS"

.segment	"ZEROPAGE"
_powerpad_cur:
	.res	2,$00
_powerpad_old:
	.res	2,$00
_powerpad_new:
	.res	2,$00
_temp_int:
	.res	2,$00
_last_step:
	.res	1,$00
_steps:
	.res	2,$00
_ones_step:
	.res	1,$00
_tens_step:
	.res	1,$00
_hundreds_step:
	.res	1,$00
_thousands_step:
	.res	1,$00
_ten_thousands_step:
	.res	1,$00
_seconds:
	.res	2,$00
_ones_seconds:
	.res	1,$00
_tens_seconds:
	.res	1,$00
_ones_minutes:
	.res	1,$00
_tens_minutes:
	.res	1,$00
_ones_hours:
	.res	1,$00
_tens_hours:
	.res	1,$00
_frame_counter:
	.res	1,$00
_step_button_lockout:
	.res	1,$00
_motion_counter:
	.res	1,$00
_time_since_button_press:
	.res	1,$00
_motion:
	.res	1,$00
_was_running:
	.res	1,$00
_was_walking:
	.res	1,$00
_largeindex:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ add_step (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_step: near

.segment	"CODE"

;
; if(step_button_lockout > 0){
;
	lda     _step_button_lockout
;
; return; //still in lockout period
;
	beq     L06E6
;
; }
;
	rts
;
; time_since_button_press = 0;
;
L06E6:	sta     _time_since_button_press
;
; steps++;
;
	lda     _steps
	ldx     _steps+1
	clc
	adc     #$01
	bcc     L0575
	inx
L0575:	sta     _steps
	stx     _steps+1
;
; step_button_lockout = FRAMES_PER_STEP; //lock out for a few frames to avoid double counting
;
	lda     #$0C
	sta     _step_button_lockout
;
; if(ones_step == 9){
;
	lda     _ones_step
	cmp     #$09
	jne     L06E5
;
; ones_step = 0;
;
	lda     #$00
	sta     _ones_step
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jsr     _one_vram_buffer
;
; if(tens_step == 9){
;
	lda     _tens_step
	cmp     #$09
	jne     L06E4
;
; tens_step = 0;
;
	lda     #$00
	sta     _tens_step
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; if(hundreds_step == 9){
;
	lda     _hundreds_step
	cmp     #$09
	bne     L06E3
;
; hundreds_step = 0;
;
	lda     #$00
	sta     _hundreds_step
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; if(thousands_step == 9){
;
	lda     _thousands_step
	cmp     #$09
	bne     L06E2
;
; thousands_step = 0;
;
	lda     #$00
	sta     _thousands_step
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; if(ten_thousands_step == 9){
;
	lda     _ten_thousands_step
	cmp     #$09
	bne     L06E1
;
; ten_thousands_step = 0;
;
	lda     #$00
	sta     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
;
; } else {
;
	jmp     _one_vram_buffer
;
; ten_thousands_step++;
;
L06E1:	inc     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	lda     _ten_thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
;
; } else {
;
	jmp     _one_vram_buffer
;
; thousands_step++;
;
L06E2:	inc     _thousands_step
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
;
; } else {
;
	jmp     _one_vram_buffer
;
; hundreds_step++;
;
L06E3:	inc     _hundreds_step
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jmp     _one_vram_buffer
;
; tens_step++;
;
L06E4:	inc     _tens_step
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jmp     _one_vram_buffer
;
; ones_step++;
;
L06E5:	inc     _ones_step
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ add_second (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_add_second: near

.segment	"CODE"

;
; seconds++;
;
	lda     _seconds
	ldx     _seconds+1
	clc
	adc     #$01
	bcc     L04DE
	inx
L04DE:	sta     _seconds
	stx     _seconds+1
;
; if(ones_seconds == 9){
;
	lda     _ones_seconds
	cmp     #$09
	jne     L06F0
;
; ones_seconds = 0;
;
	lda     #$00
	sta     _ones_seconds
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jsr     _one_vram_buffer
;
; if(tens_seconds == 5){
;
	lda     _tens_seconds
	cmp     #$05
	jne     L06EF
;
; tens_seconds = 0;
;
	lda     #$00
	sta     _tens_seconds
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; if(ones_minutes == 9){
;
	lda     _ones_minutes
	cmp     #$09
	jne     L06EE
;
; ones_minutes = 0;
;
	lda     #$00
	sta     _ones_minutes
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; if(tens_minutes == 5){
;
	lda     _tens_minutes
	cmp     #$05
	bne     L06ED
;
; tens_minutes = 0;
;
	lda     #$00
	sta     _tens_minutes
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; if(ones_hours == 9){
;
	lda     _ones_hours
	cmp     #$09
	bne     L06EC
;
; ones_hours = 0;
;
	lda     #$00
	sta     _ones_hours
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; if(tens_hours == 2){
;
	lda     _tens_hours
	cmp     #$02
	bne     L06EB
;
; tens_hours = 0;
;
	lda     #$00
	sta     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
;
; } else {
;
	jmp     _one_vram_buffer
;
; tens_hours++;
;
L06EB:	inc     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	lda     _tens_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
;
; } else {
;
	jmp     _one_vram_buffer
;
; ones_hours++;
;
L06EC:	inc     _ones_hours
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
;
; } else {
;
	jmp     _one_vram_buffer
;
; tens_minutes++;
;
L06ED:	inc     _tens_minutes
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
;
; } else {
;
	jmp     _one_vram_buffer
;
; ones_minutes++;
;
L06EE:	inc     _ones_minutes
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jmp     _one_vram_buffer
;
; tens_seconds++;
;
L06EF:	inc     _tens_seconds
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jmp     _one_vram_buffer
;
; ones_seconds++;
;
L06F0:	inc     _ones_seconds
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ initial_steps_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_steps_conversion: near

.segment	"CODE"

;
; temp_int = steps;
;
	lda     _steps
	ldx     _steps+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _tens_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; hundreds_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _hundreds_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _thousands_step
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ten_thousands_step = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ten_thousands_step
;
; one_vram_buffer(0x30+ten_thousands_step, NTADR_A(10, 4));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8A
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+thousands_step, NTADR_A(11, 4));
;
	lda     _thousands_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+hundreds_step, NTADR_A(13, 4));
;
	lda     _hundreds_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8D
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_step, NTADR_A(14, 4));
;
	lda     _tens_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_step, NTADR_A(15, 4));
;
	lda     _ones_step
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$8F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ initial_timer_conversion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_initial_timer_conversion: near

.segment	"CODE"

;
; temp_int = seconds;
;
	lda     _seconds
	ldx     _seconds+1
	sta     _temp_int
	stx     _temp_int+1
;
; ones_seconds = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_seconds
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_seconds = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_seconds
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_minutes = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_minutes
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_minutes = temp_int % 6;
;
	jsr     pushax
	lda     #$06
	jsr     tosumoda0
	sta     _tens_minutes
;
; temp_int = temp_int / 6;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$06
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; ones_hours = temp_int % 10;
;
	jsr     pushax
	lda     #$0A
	jsr     tosumoda0
	sta     _ones_hours
;
; temp_int = temp_int / 10;
;
	lda     _temp_int
	ldx     _temp_int+1
	jsr     pushax
	lda     #$0A
	jsr     tosudiva0
	sta     _temp_int
	stx     _temp_int+1
;
; tens_hours = temp_int % 3;
;
	jsr     pushax
	lda     #$03
	jsr     tosumoda0
	sta     _tens_hours
;
; one_vram_buffer(0x30+tens_hours, NTADR_A(8, 2));
;
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$48
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_hours, NTADR_A(9, 2));
;
	lda     _ones_hours
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$49
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_minutes, NTADR_A(11, 2));
;
	lda     _tens_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4B
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_minutes, NTADR_A(12, 2));
;
	lda     _ones_minutes
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4C
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+tens_seconds, NTADR_A(14, 2));
;
	lda     _tens_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4E
	jsr     _one_vram_buffer
;
; one_vram_buffer(0x30+ones_seconds, NTADR_A(15, 2));
;
	lda     _ones_seconds
	clc
	adc     #$30
	jsr     pusha
	ldx     #$20
	lda     #$4F
	jmp     _one_vram_buffer

.endproc

; ---------------------------------------------------------------
; void __near__ check_motion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_motion: near

.segment	"CODE"

;
; if((powerpad_cur & 0x0F) && (powerpad_cur & 0xF0) && time_since_button_press < 180){
;
	lda     _powerpad_cur
	and     #$0F
	beq     L05F1
	lda     _powerpad_cur
	and     #$F0
	beq     L05F1
	lda     _time_since_button_press
	cmp     #$B4
	bcs     L05F1
;
; was_walking = 1;
;
	lda     #$01
	sta     _was_walking
;
; }else if(powerpad_cur == 0 && time_since_button_press < 60){ //nothing is pressed
;
	rts
L05F1:	lda     _powerpad_cur
	ora     _powerpad_cur+1
	bne     L06F4
	lda     _time_since_button_press
	cmp     #$3C
	bcc     L06F5
L06F4:	rts
;
; was_running = 1;
;
L06F5:	lda     #$01
	sta     _was_running
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ update_motion (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_motion: near

.segment	"CODE"

;
; if(was_running){
;
	lda     _was_running
	beq     L0603
;
; motion = RUNNING;
;
	lda     #$00
	sta     _motion
;
; motion_counter = MOTION_HOLD_FRAMES;
;
	lda     #$B4
	sta     _motion_counter
;
; else if(was_walking){
;
	jmp     L06F6
L0603:	lda     _was_walking
	beq     L060A
;
; motion = WALKING;
;
	lda     #$01
	sta     _motion
;
; motion_counter = MOTION_HOLD_FRAMES;
;
	lda     #$B4
	sta     _motion_counter
;
; else {
;
	jmp     L06F6
;
; motion = STANDING;
;
L060A:	lda     #$02
	sta     _motion
;
; was_walking = 0;
;
L06F6:	lda     #$00
	sta     _was_walking
;
; was_running = 0;
;
	sta     _was_running
;
; if(motion == WALKING){
;
	lda     _motion
	cmp     #$01
	bne     L06F7
;
; multi_vram_buffer_horz("WALK ", 5, NTADR_A(2, 6));
;
	jsr     decsp3
	lda     #<(L061A)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L061A)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$C2
	jsr     _multi_vram_buffer_horz
;
; if(motion == RUNNING){
;
L06F7:	lda     _motion
	bne     L06F8
;
; multi_vram_buffer_horz("RUN  ", 5, NTADR_A(2, 6));
;
	jsr     decsp3
	lda     #<(L0626)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0626)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$C2
	jsr     _multi_vram_buffer_horz
;
; if(motion == STANDING){
;
L06F8:	lda     _motion
	cmp     #$02
	bne     L062F
;
; multi_vram_buffer_horz("STAND", 5, NTADR_A(2, 6));
;
	jsr     decsp3
	lda     #<(L0632)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0632)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$C2
	jmp     _multi_vram_buffer_horz
;
; }
;
L062F:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ load_room (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_load_room: near

.segment	"CODE"

;
; ppu_off();
;
	jsr     _ppu_off
;
; vram_adr(NAMETABLE_A);
;
	ldx     #$20
	lda     #$00
	jsr     _vram_adr
;
; for (largeindex = 0; largeindex < 1024; ++largeindex)
;
	lda     #$00
	sta     _largeindex
	sta     _largeindex+1
L06D0:	ldx     _largeindex+1
	cpx     #$04
	bcs     L06D1
;
; vram_put(Track[largeindex]);
;
	lda     #<(_Track)
	sta     ptr1
	lda     #>(_Track)
	clc
	adc     _largeindex+1
	sta     ptr1+1
	ldy     _largeindex
	lda     (ptr1),y
	jsr     _vram_put
;
; flush_vram_update2();
;
	jsr     _flush_vram_update2
;
; for (largeindex = 0; largeindex < 1024; ++largeindex)
;
	inc     _largeindex
	bne     L06D0
	inc     _largeindex+1
	jmp     L06D0
;
; ppu_on_all();
;
L06D1:	jmp     _ppu_on_all

.endproc

; ---------------------------------------------------------------
; void __near__ process_powerpad (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_process_powerpad: near

.segment	"CODE"

;
; powerpad_new = (powerpad_cur^powerpad_old)&powerpad_cur;
;
	lda     _powerpad_old
	eor     _powerpad_cur
	sta     ptr1
	lda     _powerpad_old+1
	eor     _powerpad_cur+1
	sta     ptr1+1
	lda     _powerpad_cur
	and     ptr1
	sta     _powerpad_new
	lda     _powerpad_cur+1
	and     ptr1+1
	sta     _powerpad_new+1
;
; powerpad_old = powerpad_cur;
;
	lda     _powerpad_cur+1
	sta     _powerpad_old+1
	lda     _powerpad_cur
	sta     _powerpad_old
;
; } 
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); // screen off
;
	jsr     _ppu_off
;
; pal_bg(palette_bg);
;
	lda     #<(_palette_bg)
	ldx     #>(_palette_bg)
	jsr     _pal_bg
;
; pal_spr(palette_sprites);
;
	lda     #<(_palette_sprites)
	ldx     #>(_palette_sprites)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; clear_vram_buffer();
;
	jsr     _clear_vram_buffer
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; multi_vram_buffer_horz("STEPS:  00,000", 14, NTADR_A(2, 4));
;
	jsr     decsp3
	lda     #<(L0436)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0436)
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$82
	jsr     _multi_vram_buffer_horz
;
; multi_vram_buffer_horz("TIME: 00:00:00", 14, NTADR_A(2, 2));
;
	jsr     decsp3
	lda     #<(L0440)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0440)
	sta     (sp),y
	lda     #$0E
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$42
	jsr     _multi_vram_buffer_horz
;
; ppu_on_all(); // turn on screen
;
	jsr     _ppu_on_all
;
; steps = 0;
;
	lda     #$00
	sta     _steps
	sta     _steps+1
;
; seconds = 0;
;
	sta     _seconds
	sta     _seconds+1
;
; initial_steps_conversion();
;
	jsr     _initial_steps_conversion
;
; initial_timer_conversion();
;
	jsr     _initial_timer_conversion
;
; motion = STANDING;
;
	lda     #$02
	sta     _motion
;
; motion_counter = 0;
;
	lda     #$00
	sta     _motion_counter
;
; multi_vram_buffer_horz("STAND", 5, NTADR_A(2, 6));
;
	jsr     decsp3
	lda     #<(L0455)
	ldy     #$01
	sta     (sp),y
	iny
	lda     #>(L0455)
	sta     (sp),y
	lda     #$05
	ldy     #$00
	sta     (sp),y
	ldx     #$20
	lda     #$C2
	jsr     _multi_vram_buffer_horz
;
; load_room();
;
	jsr     _load_room
;
; ppu_wait_nmi(); // wait till beginning of the frame
;
L045F:	jsr     _ppu_wait_nmi
;
; ++frame_counter;
;
	inc     _frame_counter
;
; if(time_since_button_press < 255){
;
	lda     _time_since_button_press
	cmp     #$FF
	bcs     L06F9
;
; ++time_since_button_press;
;
	inc     _time_since_button_press
;
; if(step_button_lockout > 0){
;
L06F9:	lda     _step_button_lockout
	beq     L06FA
;
; --step_button_lockout;
;
	dec     _step_button_lockout
;
; if(motion_counter > 0){
;
L06FA:	lda     _motion_counter
	beq     L06FB
;
; --motion_counter;
;
	dec     _motion_counter
;
; if(frame_counter >= 60){
;
L06FB:	lda     _frame_counter
	cmp     #$3C
	bcc     L046E
;
; frame_counter = 0;
;
	lda     #$00
	sta     _frame_counter
;
; add_second();
;
	jsr     _add_second
;
; oam_clear();
;
L046E:	jsr     _oam_clear
;
; powerpad_cur = read_powerpad(1);
;
	lda     #$01
	jsr     _read_powerpad
	sta     _powerpad_cur
	stx     _powerpad_cur+1
;
; process_powerpad(); // goes after the read
;
	jsr     _process_powerpad
;
; check_motion();
;
	jsr     _check_motion
;
; if(motion_counter == 0){
;
	lda     _motion_counter
	bne     L0479
;
; update_motion();
;
	jsr     _update_motion
;
; if(powerpad_new & POWERPAD_1){
;
L0479:	lda     _powerpad_new+1
	and     #$10
	beq     L047C
;
; oam_spr(84, 83, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_2){
;
L047C:	lda     _powerpad_new+1
	and     #$40
	beq     L0484
;
; oam_spr(100, 83, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_3){
;
L0484:	lda     _powerpad_new+1
	and     #$20
	beq     L048C
;
; oam_spr(116, 83, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_4){
;
L048C:	lda     _powerpad_new+1
	and     #$80
	beq     L0494
;
; oam_spr(132, 83, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$53
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_5){
;
L0494:	lda     _powerpad_new+1
	and     #$04
	beq     L049C
;
; oam_spr(84, 107, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_6){
;
L049C:	lda     _powerpad_new
	and     #$40
	beq     L04A4
;
; oam_spr(100, 107, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_7){
;
L04A4:	lda     _powerpad_new
	and     #$01
	beq     L04AC
;
; oam_spr(116, 107, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_8){
;
L04AC:	lda     _powerpad_new+1
	and     #$02
	beq     L04B4
;
; oam_spr(132, 107, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$6B
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_9){
;
L04B4:	lda     _powerpad_new+1
	and     #$01
	beq     L04BC
;
; oam_spr(84, 131, 0, 0);
;
	jsr     decsp3
	lda     #$54
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_10){
;
L04BC:	lda     _powerpad_new
	and     #$10
	beq     L04C4
;
; oam_spr(100, 131, 0, 0);
;
	jsr     decsp3
	lda     #$64
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_11){
;
L04C4:	lda     _powerpad_new
	and     #$04
	beq     L04CC
;
; oam_spr(116, 131, 0, 0);
;
	jsr     decsp3
	lda     #$74
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; if(powerpad_new & POWERPAD_12){
;
L04CC:	lda     _powerpad_new+1
	and     #$08
	jeq     L045F
;
; oam_spr(132, 131, 0, 0);
;
	jsr     decsp3
	lda     #$84
	ldy     #$02
	sta     (sp),y
	lda     #$83
	dey
	sta     (sp),y
	lda     #$00
	dey
	sta     (sp),y
	jsr     _oam_spr
;
; add_step();
;
	jsr     _add_step
;
; while (1){
;
	jmp     L045F

.endproc

