;this file for FamiTone2 library generated by text2data tool

MarathonSongs_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env0,@env5
	.byte $00
	.byte $30 ;instrument $09
	.word @env3,@env0,@env6
	.byte $00
	.byte $30 ;instrument $0a
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c0
	.byte $00,$0f
@env2:
	.byte $cf,$cc,$ca,$00,$02
@env3:
	.byte $cf,$ce,$c8,$c5,$c2,$c1,$c0,$00,$06
@env4:
	.byte $cf,$cd,$c7,$c5,$c0,$00,$04
@env5:
	.byte $c4,$c0,$c0,$00,$00
@env6:
	.byte $ff,$80,$00,$01


@song0ch0:
	.byte $fb,$08
@song0ch0loop:
@ref0:
	.byte $80,$1e,$29,$2c,$30,$8d,$31,$2d,$28,$85,$1e,$24,$1e,$24,$83,$1f
	.byte $22,$85
@ref1:
	.byte $2c,$85,$3a,$36,$87,$29,$1e,$85,$24,$85,$30,$2c,$28,$87,$3a,$36
	.byte $85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref2:
	.byte $bf
@ref3:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref4:
	.byte $82,$1e,$85,$28,$95,$24,$85,$1e,$95
@ref5:
	.byte $1e,$85,$28,$95,$24,$85,$1e,$95
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref6:
	.byte $84,$08,$85,$86,$18,$85,$84,$08,$85,$86,$18,$85,$84,$08,$85,$86
	.byte $18,$85,$84,$08,$85,$86,$18,$85
	.byte $ff,$10
	.word @ref6
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref8:
	.byte $bf
@ref9:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
